#!/usr/bin/env bun
/**
 * Raw data editor server.
 * Serves the editor app + provides API routes for reading/writing game.data.json.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ParsedBook } from "../../lib/data/types.js";
import { emitBooks, formatYaml } from "../../lib/parser/emit.js";
import { loadGrammars, parseEntry } from "../../lib/parser/index.js";
import type { EffectWithMeta } from "../../lib/parser/schema/effects.js";

const port = Number(process.env.PORT ?? 3002);
const root = resolve(import.meta.dirname ?? ".", "../..");
const jsonPath = resolve(root, "data/raw/game.data.json");
const booksOutPath = resolve(root, "data/yaml/books.yaml");
const affixesOutPath = resolve(root, "data/yaml/affixes.yaml");

// ── Types ──────────────────────────────────────────────

interface AffixEntry {
	text: string;
	effects: Record<string, unknown>[];
}

interface BookEntry {
	school: string;
	skill: { text: string; effects: Record<string, unknown>[] };
	primaryAffix?: {
		name: string;
		text: string;
		effects: Record<string, unknown>[];
	};
	exclusiveAffix?: {
		name: string;
		text: string;
		effects: Record<string, unknown>[];
	};
	xuan?: {
		text: string;
		effects: Record<string, unknown>[];
	};
}

interface GameData {
	version: number;
	books: Record<string, BookEntry>;
	affixes: {
		universal: Record<string, AffixEntry>;
		school: Record<string, Record<string, AffixEntry>>;
	};
}

// ── Load grammars at startup ───────────────────────────

await loadGrammars();

// ── Helpers ────────────────────────────────────────────

function readGameData(): GameData {
	return JSON.parse(readFileSync(jsonPath, "utf-8")) as GameData;
}

function generateYaml(gameData: GameData): {
	booksCount: number;
	affixesCount: number;
} {
	// Books
	const parsedBooks = new Map<string, ParsedBook>();
	for (const [name, book] of Object.entries(gameData.books)) {
		const parsed: ParsedBook = {
			school: book.school,
			skillText: book.skill?.text,
			affixText: book.primaryAffix?.text,
			exclusiveAffixText: book.exclusiveAffix?.text,
			skill: (book.skill?.effects ?? []) as EffectWithMeta[],
		};
		if (book.primaryAffix) {
			parsed.primaryAffix = {
				name: book.primaryAffix.name,
				effects: (book.primaryAffix.effects ?? []) as EffectWithMeta[],
			};
		}
		if (book.exclusiveAffix) {
			parsed.exclusiveAffix = {
				name: book.exclusiveAffix.name,
				effects: (book.exclusiveAffix.effects ?? []) as EffectWithMeta[],
			};
		}
		parsedBooks.set(name, parsed);
	}
	const booksData = emitBooks(parsedBooks);
	writeFileSync(booksOutPath, formatYaml(booksData));

	// Affixes
	const { universal, school } = gameData.affixes;
	const lines: string[] = [
		"# Common & school affixes — generated by gen-yaml",
		"# Regenerate with: bun scripts/gen-yaml.ts",
		"",
		"universal:",
	];
	let affixesCount = 0;
	for (const [name, d] of Object.entries(universal)) {
		affixesCount++;
		lines.push(`  ${name}:`, "    text: |");
		for (const l of d.text.split("\n")) lines.push(`      ${l}`);
		lines.push("    effects:");
		for (const eff of d.effects) {
			const entries = Object.entries(eff);
			lines.push(`      - ${entries[0][0]}: ${JSON.stringify(entries[0][1])}`);
			for (const [k, v] of entries.slice(1))
				lines.push(`        ${k}: ${JSON.stringify(v)}`);
		}
	}
	lines.push("", "school:");
	for (const [sn, affixes] of Object.entries(school)) {
		lines.push(`  ${sn}:`);
		for (const [name, d] of Object.entries(affixes)) {
			affixesCount++;
			lines.push(`    ${name}:`, "      text: |");
			for (const l of d.text.split("\n")) lines.push(`        ${l}`);
			lines.push("      effects:");
			for (const eff of d.effects) {
				const entries = Object.entries(eff);
				lines.push(
					`        - ${entries[0][0]}: ${JSON.stringify(entries[0][1])}`,
				);
				for (const [k, v] of entries.slice(1))
					lines.push(`          ${k}: ${JSON.stringify(v)}`);
			}
		}
	}
	writeFileSync(affixesOutPath, `${lines.join("\n")}\n`);

	return { booksCount: parsedBooks.size, affixesCount };
}

// ── Server ─────────────────────────────────────────────

Bun.serve({
	port,
	async fetch(req) {
		const url = new URL(req.url);
		const p = url.pathname;

		// --- API routes ---

		if (p === "/api/data" && req.method === "GET") {
			return Response.json(readGameData());
		}

		if (p === "/api/save" && req.method === "POST") {
			try {
				const body = await req.json();
				writeFileSync(jsonPath, `${JSON.stringify(body, null, 2)}\n`);
				return Response.json({ ok: true });
			} catch (e) {
				return Response.json(
					{ ok: false, error: (e as Error).message },
					{ status: 400 },
				);
			}
		}

		if (p === "/api/parse" && req.method === "POST") {
			try {
				const { grammarName, text, entryPoint } = (await req.json()) as {
					grammarName: string;
					text: string;
					entryPoint: string;
				};
				const effects = parseEntry(grammarName, text, entryPoint);
				return Response.json({ effects });
			} catch (e) {
				return Response.json({ effects: [], error: (e as Error).message });
			}
		}

		if (p === "/api/gen-yaml" && req.method === "GET") {
			try {
				const gameData = readGameData();
				const result = generateYaml(gameData);
				return Response.json({ ok: true, ...result });
			} catch (e) {
				return Response.json(
					{ ok: false, error: (e as Error).message },
					{ status: 500 },
				);
			}
		}

		// --- Static files ---

		if (p === "/" || p === "/index.html") {
			return new Response(Bun.file("app/editor/index.html"));
		}

		if (p.endsWith(".tsx") || p.endsWith(".ts")) {
			try {
				const r = await Bun.build({
					entrypoints: [`app/editor${p}`],
					format: "esm",
					target: "browser",
					minify: false,
				});
				if (r.success && r.outputs.length) {
					return new Response(await r.outputs[0].text(), {
						headers: { "Content-Type": "application/javascript" },
					});
				}
			} catch {}
			return new Response("Build error", { status: 500 });
		}

		const f = Bun.file(`app/editor${p}`);
		if (await f.exists()) return new Response(f);

		return new Response("Not found", { status: 404 });
	},
});

console.log(`Editor: http://localhost:${port}`);
