/**
 * Layer: Common & School Affix Parser
 *
 * Reads 通用词缀.md (universal) and 修为词缀.md (school) —
 * 2-column tables (词缀 | 效果描述).
 * Parses each affix into typed EffectRow[] using the generic
 * affix pipeline (same AFFIX_EXTRACTORS as exclusive affixes).
 */

import { cleanEffects, type EffectRow, formatEffect } from "./emit.js";
import { SCHOOL_MAP, type SplitCell, splitCell } from "./md-table.js";
import { genericAffixParse } from "./split.js";

export interface AffixEntry {
	name: string;
	school?: string; // undefined for universal, "Sword"/"Spell"/etc for school
	cell: SplitCell;
}

/**
 * Read 通用词缀.md — single 2-column table (词缀 | 效果描述).
 */
export function readUniversalAffixTable(markdown: string): AffixEntry[] {
	return readTwoColumnTable(markdown);
}

/**
 * Read 修为词缀.md — school-grouped 2-column tables.
 */
export function readSchoolAffixTable(markdown: string): AffixEntry[] {
	const lines = markdown.split("\n");
	const entries: AffixEntry[] = [];
	let currentSchool = "";

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		const schoolMatch = line.match(/^####\s+(剑修|法修|魔修|体修)/);
		if (schoolMatch) {
			currentSchool = SCHOOL_MAP[schoolMatch[1]];
			continue;
		}

		if (!currentSchool) continue;
		if (!/^\|\s*词缀\s*\|/.test(line)) continue;

		// Skip separator row
		i += 2;

		while (i < lines.length && lines[i].startsWith("|")) {
			const cells = lines[i]
				.split("|")
				.slice(1, -1)
				.map((c) => c.trim());

			if (cells.length >= 2) {
				const nameMatch = cells[0].match(/【(.+?)】/);
				const name = nameMatch ? nameMatch[1] : cells[0].trim();
				const effectText = cells[1] || "";

				if (name && effectText) {
					entries.push({
						name,
						school: currentSchool,
						cell: splitCell(stripBackticks(effectText)),
					});
				}
			}
			i++;
		}
	}

	return entries;
}

/**
 * Read a single 2-column table (词缀 | 效果描述) without school context.
 */
function readTwoColumnTable(markdown: string): AffixEntry[] {
	const lines = markdown.split("\n");
	const entries: AffixEntry[] = [];

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		if (!/^\|\s*词缀\s*\|/.test(line)) continue;

		// Skip separator row
		i += 2;

		while (i < lines.length && lines[i].startsWith("|")) {
			const cells = lines[i]
				.split("|")
				.slice(1, -1)
				.map((c) => c.trim());

			if (cells.length >= 2) {
				const nameMatch = cells[0].match(/【(.+?)】/);
				const name = nameMatch ? nameMatch[1] : cells[0].trim();
				const effectText = cells[1] || "";

				if (name && effectText) {
					entries.push({
						name,
						cell: splitCell(stripBackticks(effectText)),
					});
				}
			}
			i++;
		}
	}

	return entries;
}

/** Strip markdown backtick formatting from effect text */
function stripBackticks(text: string): string {
	return text.replace(/`/g, "");
}

export interface AffixData {
	effects: EffectRow[];
}

export interface CommonAffixResult {
	universal: Record<string, AffixData>;
	school: Record<string, Record<string, AffixData>>;
	warnings: string[];
}

/**
 * Parse universal + school affixes into structured data.
 */
export function parseCommonAffixes(
	universalMd: string,
	schoolMd: string,
): CommonAffixResult {
	const warnings: string[] = [];
	const universal: Record<string, AffixData> = {};
	const school: Record<string, Record<string, AffixData>> = {};

	// Parse universal affixes
	const universalEntries = readUniversalAffixTable(universalMd);
	for (const entry of universalEntries) {
		const effects = genericAffixParse(entry.cell, {}, { lastTierOnly: true });
		if (effects.length === 0) {
			warnings.push(`Universal affix ${entry.name}: no effects extracted`);
		}
		universal[entry.name] = { effects: cleanEffects(effects) };
	}

	// Parse school affixes
	const schoolEntries = readSchoolAffixTable(schoolMd);
	for (const entry of schoolEntries) {
		const schoolName = entry.school!;
		if (!school[schoolName]) {
			school[schoolName] = {};
		}

		const effects = genericAffixParse(entry.cell, {}, { lastTierOnly: true });
		if (effects.length === 0) {
			warnings.push(
				`School affix ${entry.name} (${schoolName}): no effects extracted`,
			);
		}
		school[schoolName][entry.name] = { effects: cleanEffects(effects) };
	}

	return { universal, school, warnings };
}

/**
 * Format affixes as YAML string.
 */
export function formatAffixesYaml(result: CommonAffixResult): string {
	const lines: string[] = [
		"# Common & school affixes — generated by parse-affixes",
		"# Regenerate with: bun app/parse-affixes.ts",
		"",
		"universal:",
	];

	for (const [name, data] of Object.entries(result.universal)) {
		lines.push(`  ${name}:`);
		lines.push("    effects:");
		for (const effect of data.effects) {
			lines.push(...formatEffect(effect, 6));
		}
	}

	lines.push("");
	lines.push("school:");
	for (const [schoolName, affixes] of Object.entries(result.school)) {
		lines.push(`  ${schoolName}:`);
		for (const [name, data] of Object.entries(affixes)) {
			lines.push(`    ${name}:`);
			lines.push("      effects:");
			for (const effect of data.effects) {
				lines.push(...formatEffect(effect, 8));
			}
		}
	}

	return `${lines.join("\n")}\n`;
}
