/**
 * Layer: YAML Emitter
 *
 * Converts parsed book data into YAML-compatible objects
 * matching the effects.yaml format.
 */

import type { BookData, EffectRow, StateDef } from "../data/types.js";
import type { ParsedBook } from "./split.js";

export type {
	AffixSection,
	BookData,
	EffectRow,
	StateDef,
} from "../data/types.js";

/**
 * Convert parsed books to the effects.yaml books structure.
 */
export function emitBooks(
	parsedBooks: Map<string, ParsedBook>,
): Record<string, BookData> {
	const books: Record<string, BookData> = {};

	for (const [name, parsed] of parsedBooks) {
		const book: BookData = {
			school: parsed.school,
		};

		if (parsed.skillText) book.skill_text = parsed.skillText;
		if (parsed.affixText) book.affix_text = parsed.affixText;

		if (parsed.states && Object.keys(parsed.states).length > 0) {
			book.states = parsed.states;
		}

		if (parsed.skill.length > 0) {
			book.skill = cleanEffects(parsed.skill);
		}

		if (parsed.primaryAffix) {
			book.primary_affix = {
				name: parsed.primaryAffix.name,
				effects: cleanEffects(parsed.primaryAffix.effects),
			};
		}

		if (parsed.exclusiveAffix) {
			book.exclusive_affix = {
				name: parsed.exclusiveAffix.name,
				effects: cleanEffects(parsed.exclusiveAffix.effects),
			};
		}

		books[name] = book;
	}

	return books;
}

/**
 * Clean effect rows: remove undefined values, ensure correct types.
 */
export function cleanEffects(effects: EffectRow[]): EffectRow[] {
	return effects.map((e) => {
		const clean: EffectRow = { type: e.type };
		for (const [k, v] of Object.entries(e)) {
			if (v !== undefined) {
				clean[k] = v;
			}
		}
		return clean;
	});
}

/**
 * Format books as YAML string matching effects.yaml format.
 */
export function formatYaml(books: Record<string, BookData>): string {
	const lines: string[] = [
		"# Divine Book effects — generated by parse-main-skills",
		"# Regenerate with: bun app/parse-main-skills.ts",
		"books:",
	];

	for (const [name, book] of Object.entries(books)) {
		lines.push(`  ${name}:`);
		lines.push(`    school: ${book.school}`);

		if (book.skill_text) {
			lines.push(`    skill_text: |`);
			for (const line of book.skill_text.split("\n")) {
				lines.push(`      ${line}`);
			}
		}
		if (book.affix_text) {
			lines.push(`    affix_text: |`);
			for (const line of book.affix_text.split("\n")) {
				lines.push(`      ${line}`);
			}
		}

		if (book.states && Object.keys(book.states).length > 0) {
			lines.push("    states:");
			for (const [sName, sDef] of Object.entries(book.states)) {
				lines.push(...formatStateDef(sName, sDef, 6));
			}
		}

		if (book.skill && book.skill.length > 0) {
			lines.push("    skill:");
			for (const effect of book.skill) {
				lines.push(...formatEffect(effect, 6));
			}
		}

		if (book.primary_affix) {
			lines.push("    primary_affix:");
			lines.push(`      name: ${book.primary_affix.name}`);
			if (book.primary_affix.effects.length > 0) {
				lines.push("      effects:");
				for (const effect of book.primary_affix.effects) {
					lines.push(...formatEffect(effect, 8));
				}
			}
		}

		if (book.exclusive_affix) {
			lines.push("    exclusive_affix:");
			lines.push(`      name: ${book.exclusive_affix.name}`);
			if (book.exclusive_affix.effects.length > 0) {
				lines.push("      effects:");
				for (const effect of book.exclusive_affix.effects) {
					lines.push(...formatEffect(effect, 8));
				}
			}
		}
	}

	return `${lines.join("\n")}\n`;
}

function formatStateDef(name: string, def: StateDef, indent: number): string[] {
	const pad = " ".repeat(indent);
	const lines: string[] = [];
	lines.push(`${pad}${name}:`);
	lines.push(`${pad}  target: ${def.target}`);
	lines.push(`${pad}  duration: ${def.duration}`);
	if (def.max_stacks !== undefined) {
		lines.push(`${pad}  max_stacks: ${def.max_stacks}`);
	}
	if (def.trigger) {
		lines.push(`${pad}  trigger: ${def.trigger}`);
	}
	if (def.chance !== undefined) {
		lines.push(`${pad}  chance: ${def.chance}`);
	}
	if (def.dispellable !== undefined) {
		lines.push(`${pad}  dispellable: ${def.dispellable}`);
	}
	if (def.children && def.children.length > 0) {
		lines.push(`${pad}  children: [${def.children.join(", ")}]`);
	}
	if (def.per_hit_stack) {
		lines.push(`${pad}  per_hit_stack: true`);
	}
	return lines;
}

export function formatEffect(effect: EffectRow, indent: number): string[] {
	const pad = " ".repeat(indent);
	const lines: string[] = [];
	const entries = Object.entries(effect);

	// type comes first
	const typeEntry = entries.find(([k]) => k === "type");
	if (typeEntry) {
		lines.push(`${pad}- type: ${typeEntry[1]}`);
	}

	for (const [key, value] of entries) {
		if (key === "type") continue;

		if (key === "data_state") {
			if (Array.isArray(value)) {
				lines.push(`${pad}  data_state:`);
				for (const item of value) {
					lines.push(`${pad}    - ${item}`);
				}
			} else {
				lines.push(`${pad}  data_state: ${value}`);
			}
		} else if (typeof value === "string") {
			lines.push(`${pad}  ${key}: ${value}`);
		} else if (typeof value === "boolean") {
			lines.push(`${pad}  ${key}: ${value}`);
		} else if (typeof value === "number") {
			lines.push(`${pad}  ${key}: ${value}`);
		}
	}

	return lines;
}
