/**
 * Affix Browser — browse all affixes organized by the 7 behavioral categories.
 * Taxonomy data loaded from affix-taxonomy.json (generated by gen-affix-taxonomy.ts).
 */

import { useState } from "react";
import affixesData from "./affixes-data.json";
import taxonomyData from "./affix-taxonomy.json";
import booksData from "./books-data.json";
import {
	btnStyle,
	dialogStyle,
	dialogTitleStyle,
	labelStyle,
	overlayStyle,
	selectStyle,
	theme as T,
} from "./components.tsx";

// ── Types ───────────────────────────────────────────────────────────

interface CategoryDef {
	name: string;
	cn: string;
	desc: string;
}

interface TaxonomyAffix {
	name: string;
	source: string;
	source_type: "universal" | "school" | "primary" | "exclusive";
	categories: number[];
	effect_types: string[];
}

interface DisplayEntry extends TaxonomyAffix {
	text?: string;
	effects: { type: string; [k: string]: unknown }[];
}

// ── Load taxonomy + resolve display data ────────────────────────────

const CATEGORIES = (taxonomyData as { categories: Record<string, CategoryDef> }).categories;
const TAXONOMY_AFFIXES = (taxonomyData as { affixes: TaxonomyAffix[] }).affixes;

const allAffixes = affixesData as {
	universal: Record<string, { text?: string; effects: { type: string; [k: string]: unknown }[] }>;
	school: Record<string, Record<string, { text?: string; effects: { type: string; [k: string]: unknown }[] }>>;
};
const allBooks = (booksData as { books: Record<string, {
	affix_text?: string;
	exclusive_affix_text?: string;
	primary_affix?: { name: string; effects: { type: string; [k: string]: unknown }[] };
	exclusive_affix?: { name: string; effects: { type: string; [k: string]: unknown }[] };
}> }).books;

/** Resolve full display data for a taxonomy entry */
function resolveEntry(t: TaxonomyAffix): DisplayEntry {
	let text: string | undefined;
	let effects: { type: string; [k: string]: unknown }[] = [];

	if (t.source_type === "universal" && allAffixes.universal[t.name]) {
		text = allAffixes.universal[t.name].text;
		effects = allAffixes.universal[t.name].effects;
	} else if (t.source_type === "school") {
		for (const school of Object.values(allAffixes.school)) {
			if (school[t.name]) {
				text = school[t.name].text;
				effects = school[t.name].effects;
				break;
			}
		}
	} else if (t.source_type === "primary" && allBooks[t.source]?.primary_affix) {
		text = allBooks[t.source].affix_text;
		effects = allBooks[t.source].primary_affix?.effects ?? [];
	} else if (t.source_type === "exclusive" && allBooks[t.source]?.exclusive_affix) {
		text = allBooks[t.source].exclusive_affix_text;
		effects = allBooks[t.source].exclusive_affix?.effects ?? [];
	}

	return { ...t, text, effects };
}

const DISPLAY_INDEX: DisplayEntry[] = TAXONOMY_AFFIXES.map(resolveEntry);

// ── Component ───────────────────────────────────────────────────────

export function AffixBrowser({ onClose }: { onClose: () => void }) {
	const [selectedCategory, setSelectedCategory] = useState(0);
	const [selectedAffix, setSelectedAffix] = useState<DisplayEntry | null>(null);

	const filtered = selectedCategory === 0
		? DISPLAY_INDEX
		: DISPLAY_INDEX.filter((a) => a.categories.includes(selectedCategory));

	return (
		<div style={overlayStyle} onClick={onClose}>
			<div
				style={{ ...dialogStyle, maxHeight: "85vh", overflowY: "auto", minWidth: 600, maxWidth: 800 }}
				onClick={(e) => e.stopPropagation()}
			>
				<div style={dialogTitleStyle}>Affix Browser</div>

				<div style={{ marginBottom: 12 }}>
					<label style={labelStyle}>Category</label>
					<select
						value={selectedCategory}
						onChange={(e) => { setSelectedCategory(Number(e.target.value)); setSelectedAffix(null); }}
						style={selectStyle}
					>
						<option value={0}>All ({DISPLAY_INDEX.length})</option>
						{Object.entries(CATEGORIES).map(([id, c]) => {
							const count = DISPLAY_INDEX.filter((a) => a.categories.includes(Number(id))).length;
							return (
								<option key={id} value={id}>
									{id}. {c.cn} — {c.name} ({count})
								</option>
							);
						})}
					</select>
				</div>

				{selectedCategory > 0 && (
					<div style={{ fontSize: 11, color: T.textMuted, marginBottom: 10, textShadow: "1px 1px 2px black" }}>
						{CATEGORIES[selectedCategory]?.desc}
					</div>
				)}

				<div style={{ display: "flex", gap: 12, minHeight: 300 }}>
					{/* List */}
					<div style={{
						flex: "0 0 220px", overflowY: "auto", maxHeight: 400,
						background: "#111", borderRadius: 4, border: "1px solid #444",
						boxShadow: "inset 0 2px 5px rgba(0,0,0,0.5)",
					}}>
						{filtered.map((affix, i) => (
							<div
								key={`${affix.name}-${affix.source}-${i}`}
								onClick={() => setSelectedAffix(affix)}
								style={{
									padding: "6px 10px", cursor: "pointer",
									borderBottom: "1px solid #333",
									background: selectedAffix === affix ? `${T.goldDark}33` : "transparent",
									color: selectedAffix === affix ? T.goldLight : T.text,
									fontSize: 12, textShadow: "1px 1px 2px black",
								}}
							>
								<div style={{ fontWeight: selectedAffix === affix ? "bold" : "normal" }}>
									{affix.name}
								</div>
								<div style={{ fontSize: 10, color: T.textMuted }}>
									{affix.source} ({affix.source_type})
								</div>
							</div>
						))}
					</div>

					{/* Detail */}
					<div style={{
						flex: 1, background: "#111", borderRadius: 4, border: "1px solid #444",
						padding: 10, overflowY: "auto", maxHeight: 400,
						boxShadow: "inset 0 2px 5px rgba(0,0,0,0.5)",
					}}>
						{selectedAffix ? (
							<>
								<div style={{ fontFamily: T.heading, color: T.goldLight, fontSize: 14, marginBottom: 6, textShadow: "1px 1px 3px #000" }}>
									{selectedAffix.name}
								</div>
								<div style={{ fontSize: 11, color: T.textMuted, marginBottom: 8 }}>
									Source: {selectedAffix.source} ({selectedAffix.source_type})
									{" | "}
									{selectedAffix.categories.map((c) => `${c}.${CATEGORIES[c]?.cn}`).join(" + ")}
								</div>

								{selectedAffix.text && (
									<>
										<div style={{ color: T.goldLight, fontSize: 11, marginBottom: 2 }}>原文</div>
										<div style={{
											color: T.textMuted, whiteSpace: "pre-wrap",
											paddingLeft: 8, borderLeft: `2px solid ${T.goldDark}44`,
											fontSize: 11, marginBottom: 8, textShadow: "1px 1px 2px black",
										}}>
											{selectedAffix.text}
										</div>
									</>
								)}

								<div style={{ color: T.goldLight, fontSize: 11, marginBottom: 4 }}>Parsed Effects</div>
								{selectedAffix.effects.map((e, j) => {
									const { type, data_state, ...params } = e;
									const paramStr = Object.entries(params)
										.filter(([, v]) => v !== undefined)
										.map(([k, v]) => `${k}=${v}`)
										.join(", ");
									return (
										<div key={`${type}-${j}`} style={{ fontSize: 11, paddingLeft: 8, marginBottom: 2, color: T.text }}>
											<span style={{ color: T.sp }}>{type as string}</span>
											{paramStr ? `: ${paramStr}` : ""}
										</div>
									);
								})}
							</>
						) : (
							<div style={{ color: T.textMuted, fontSize: 12, padding: 20, textAlign: "center" }}>
								Select an affix to view details
							</div>
						)}
					</div>
				</div>

				<div style={{ display: "flex", justifyContent: "flex-end", marginTop: 12 }}>
					<button type="button" onClick={onClose} className={btnStyle}>Close</button>
				</div>
			</div>
		</div>
	);
}
