/** §2 Damage Multiplier Zones — 8 types */

import { ExecTarget, Scope, Trigger, Unit, Zone } from "../enums.js";
import type { EffectTypeDef } from "../types.js";
import {
	AttackBonusSchema,
	CritDamageBonusSchema,
	DamageIncreaseSchema,
	EnemySkillDamageReductionSchema,
	FinalDamageBonusSchema,
	FlatExtraDamageSchema,
	SkillDamageIncreaseSchema,
	TechniqueDamageIncreaseSchema,
} from "../../schemas/effect.js";

export const MULTIPLIER_DEFS: EffectTypeDef[] = [
	{
		type: "attack_bonus",
		schema: AttackBonusSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.S_coeff],
		scope: Scope.Same,
		patterns: ["(本神通施放时，会)使本(次)神通提升{x}%攻击力的效果"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.atk"],
		},
	},
	{
		type: "damage_increase",
		schema: DamageIncreaseSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_dmg],
		scope: Scope.Same,
		patterns: [
			"造成的伤害提升{x}%",
			"伤害提升{x}%",
			"提升{x}%伤害",
		],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.damage"],
		},
	},
	{
		type: "skill_damage_increase",
		schema: SkillDamageIncreaseSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_skill],
		scope: Scope.Same,
		patterns: ["本神通攻击目标时提升{x}%神通伤害", "{x}%的神通伤害加深"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.damage"],
		},
	},
	{
		type: "enemy_skill_damage_reduction",
		schema: EnemySkillDamageReductionSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_skill],
		scope: Scope.Same,
		patterns: ["目标对本神通提升{x}%神通伤害减免"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Opponent,
			writes: ["opponent.def"],
		},
	},
	{
		type: "final_damage_bonus",
		schema: FinalDamageBonusSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_final],
		scope: Scope.Same,
		patterns: ["(本神通施放时，会使本次神通的)最终伤害加深提升{x}%"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.damage"],
		},
	},
	{
		type: "crit_damage_bonus",
		schema: CritDamageBonusSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_crit],
		scope: Scope.Same,
		patterns: ["(使本神通)暴击伤害提升/提高{x}%", "致命伤害提升{x}%"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.crit_damage"],
		},
	},
	{
		type: "technique_damage_increase",
		schema: TechniqueDamageIncreaseSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.M_skill],
		scope: Scope.Same,
		patterns: ["{x}%的技能伤害加深"],
		fields: [{ name: "value", unit: Unit.PctStat }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Self,
			writes: ["self.damage"],
		},
		notes: "No data instances in normalized.data.md yet",
	},
	{
		type: "flat_extra_damage",
		schema: FlatExtraDamageSchema,
		group: "damage_multiplier_zones",
		zones: [Zone.D_flat],
		scope: Scope.Same,
		patterns: ["本神通施放/命中时，会使本次神通(额外)造成{x}%攻击力的伤害"],
		fields: [{ name: "value", unit: Unit.PctAtk }],
		exec: {
			trigger: Trigger.OnCast,
			target: ExecTarget.Opponent,
			reads: ["self.atk"],
			writes: ["opponent.hp"],
		},
	},
];
