/**
 * gen-yaml.ts — Generate books.yaml and affixes.yaml from game.data.json
 *
 * Usage:
 *   bun scripts/gen-yaml.ts                  # generate both
 *   bun scripts/gen-yaml.ts --books-only     # only books.yaml
 *   bun scripts/gen-yaml.ts --affixes-only   # only affixes.yaml
 */

import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { resolve } from "node:path";

import type { ParsedBook } from "../lib/data/types.js";
import { emitBooks, formatYaml, formatEffect } from "../lib/parser/emit.js";

// --- CLI ---

const { values } = parseArgs({
	options: {
		"books-only": { type: "boolean", default: false },
		"affixes-only": { type: "boolean", default: false },
	},
	strict: true,
});

const booksOnly = values["books-only"]!;
const affixesOnly = values["affixes-only"]!;

// --- Paths ---

const root = resolve(import.meta.dirname!, "..");
const jsonPath = resolve(root, "data/raw/game.data.json");
const booksOutPath = resolve(root, "data/yaml/books.yaml");
const affixesOutPath = resolve(root, "data/yaml/affixes.yaml");

// --- Read source ---

const gameData = JSON.parse(await Bun.file(jsonPath).text());

// --- Books ---

if (!affixesOnly) {
	const parsedBooks = new Map<string, ParsedBook>();

	for (const [name, book] of Object.entries(gameData.books) as [string, any][]) {
		const parsed: ParsedBook = {
			school: book.school,
			skillText: book.skill?.text,
			affixText: book.primaryAffix?.text,
			exclusiveAffixText: book.exclusiveAffix?.text,
			xuanText: book.xuan?.text,
			skill: book.skill?.effects ?? [],
		};

		if (book.primaryAffix) {
			parsed.primaryAffix = {
				name: book.primaryAffix.name,
				effects: book.primaryAffix.effects ?? [],
			};
		}

		if (book.exclusiveAffix) {
			parsed.exclusiveAffix = {
				name: book.exclusiveAffix.name,
				effects: book.exclusiveAffix.effects ?? [],
			};
		}

		if (book.xuan) {
			parsed.xuan = { effects: book.xuan.effects ?? [] };
		}

		parsedBooks.set(name, parsed);
	}

	const booksData = emitBooks(parsedBooks);
	const yaml = formatYaml(booksData);
	writeFileSync(booksOutPath, yaml);
	console.log(`Written books.yaml → ${booksOutPath}`);
}

// --- Affixes ---

if (!booksOnly) {
	const { universal, school } = gameData.affixes as {
		universal: Record<string, { text: string; effects: Record<string, unknown>[] }>;
		school: Record<string, Record<string, { text: string; effects: Record<string, unknown>[] }>>;
	};

	const lines: string[] = [
		"# Common & school affixes — generated by parse-affixes",
		"# Regenerate with: bun app/parse-affixes.ts",
		"",
		"universal:",
	];

	for (const [name, d] of Object.entries(universal)) {
		lines.push(`  ${name}:`, "    text: |");
		for (const l of d.text.split("\n")) lines.push(`      ${l}`);
		lines.push("    effects:");
		for (const eff of d.effects) {
			const entries = Object.entries(eff);
			lines.push(`      - ${entries[0][0]}: ${JSON.stringify(entries[0][1])}`);
			for (const [k, v] of entries.slice(1))
				lines.push(`        ${k}: ${JSON.stringify(v)}`);
		}
	}

	lines.push("", "school:");
	for (const [sn, affixes] of Object.entries(school)) {
		lines.push(`  ${sn}:`);
		for (const [name, d] of Object.entries(affixes)) {
			lines.push(`    ${name}:`, "      text: |");
			for (const l of d.text.split("\n")) lines.push(`        ${l}`);
			lines.push("      effects:");
			for (const eff of d.effects) {
				const entries = Object.entries(eff);
				lines.push(`        - ${entries[0][0]}: ${JSON.stringify(entries[0][1])}`);
				for (const [k, v] of entries.slice(1))
					lines.push(`          ${k}: ${JSON.stringify(v)}`);
			}
		}
	}

	const yamlStr = lines.join("\n") + "\n";
	writeFileSync(affixesOutPath, yamlStr);
	console.log(`Written affixes.yaml → ${affixesOutPath}`);
}
